version: '3.1'

services:

  db:
    image: mysql:8.0.13
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: db2
      MYSQL_USER: db2
      MYSQL_PASSWORD: senha123
      MYSQL_ROOT_PASSWORD: senha123
     
    security_opt:
      - seccomp:unconfined
    ports:
      - "3310:3306"
    volumes: 
      - ./my.conf:/etc/mysql/conf.d/config-file.cnf
      - ./data:/var/lib/mysql

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
  # system:
  #   image: ubuntu
  #   restart: always
  #   command:
  #   - ./bin/bash
  #   volumes:
  #   - ./src:/test


   